# Generated by Django 4.2.11 on 2024-03-06 22:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AreaFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RelocationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relocate', models.IntegerField(null=True)),
                ('location', models.IntegerField(null=True)),
                ('housing_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commute', models.IntegerField(null=True)),
                ('commute_time', models.IntegerField(default=0)),
                ('transport', models.IntegerField(null=True)),
                ('commute_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_costs', models.IntegerField(null=True)),
                ('work_from_home', models.IntegerField(null=True)),
                ('office_days', models.IntegerField(default=5)),
                ('full_time_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('extras', models.IntegerField(null=True)),
                ('area_focus', models.IntegerField(null=True)),
                ('job_role', models.IntegerField(null=True)),
                ('responsibility', models.IntegerField(null=True)),
                ('min_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('holiday_days', models.IntegerField(default=0)),
                ('schedule_type', models.IntegerField(null=True)),
                ('company_size', models.IntegerField(null=True)),
                ('bring_pet', models.IntegerField(null=True)),
                ('own_computer', models.IntegerField(null=True)),
                ('office_type', models.IntegerField(null=True)),
                ('desk_features', models.IntegerField(null=True)),
                ('social_activities', models.IntegerField(null=True)),
                ('pet_sitter', models.IntegerField(null=True)),
                ('child_care', models.IntegerField(null=True)),
                ('freelance_hire', models.IntegerField(null=True)),
                ('deadline', models.DateField()),
                ('status', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
