# Generated by Django 4.2.11 on 2024-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0002_alter_job_options_job_is_dream_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bring_pet',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Yes'), (2, 'No')], default=1, help_text='Whether pets are allowed in the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='child_care',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Yes'), (2, 'No')], default=1, help_text='Availability of child care close to the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='freelance_hire',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Yes'), (2, 'No')], default=0, help_text='If you will be invoicing the company or hired as an employee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='office_days',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Working from home'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6'), (8, '7')], default=5, help_text='Number of office days per week'),
        ),
        migrations.AlterField(
            model_name='job',
            name='office_type',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Open'), (2, 'Cubicle'), (3, 'Private')], default=0, help_text='Type of office layout'),
        ),
        migrations.AlterField(
            model_name='job',
            name='own_computer',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Yes'), (2, 'No')], default=1, help_text='Whether you need to bring your own computer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pet_sitter',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Yes'), (2, 'No')], default=1, help_text='Availability of pet sitter close to the office'),
        ),
    ]
