# Generated by Django 4.2.11 on 2024-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0003_alter_job_bring_pet_alter_job_child_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Employer',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='bring_pet',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='Whether pets are allowed in the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='child_care',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='Availability of child care close to the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1, help_text='Size of the company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='freelance_hire',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=0, help_text='If you will be invoicing the company or hired as an employee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_to_apply',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='office_days',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Work f/ home'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6'), (8, '7')], default=5, help_text='Number of office days per week'),
        ),
        migrations.AlterField(
            model_name='job',
            name='office_type',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Open'), (2, 'Cubicle'), (3, 'Private')], default=0, help_text='Type of office layout'),
        ),
        migrations.AlterField(
            model_name='job',
            name='own_computer',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='Whether you need to bring your own computer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(help_text='pay for the job', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='pet_sitter',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='Availability of pet sitter close to the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibility',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Manager'), (2, 'Supervisor'), (3, 'Team Leader'), (4, 'Employee')], default=3, help_text='Job responsibility level', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_type',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Fixed'), (2, 'Flexible'), (3, 'Remote')], default=0, help_text='Type of work schedule'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='starting_time',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, '6:00'), (2, '6:30'), (3, '7:00'), (4, '7:30'), (5, '8:00'), (6, '8:30'), (7, '9:00'), (8, '9:30'), (9, '10:00'), (10, '10:30'), (11, '11:00'), (12, '11:30'), (13, '12:00'), (14, '12:30'), (15, '1:00'), (16, '1:30'), (17, '2:00'), (18, '2:30'), (19, '3:00'), (20, '3:30'), (21, '4:00'), (22, '4:30'), (23, '5:00'), (24, '5:30'), (25, '6:00'), (26, '6:30'), (27, '7:00'), (28, '7:30'), (29, '8:00'), (30, '8:30'), (31, '9:00'), (32, '9:30'), (33, '10:00'), (34, '10:30'), (35, '11:00'), (36, '11:30'), (37, '12:00'), (38, '12:30'), (39, '1:00'), (40, '1:30'), (41, '2:00'), (42, '2:30'), (43, '3:00'), (44, '3:30'), (45, '4:00'), (46, '4:30'), (47, '5:00'), (48, '5:30')], default=0, help_text='Starting time of the work'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Considering'), (2, 'Applied'), (3, 'Interviewing'), (4, 'Rejected'), (5, 'Accepted')], default=0, help_text='Current status of the job application'),
        ),
    ]
