# Generated by Django 4.2.11 on 2024-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0004_alter_job_bring_pet_alter_job_child_care_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='office_days',
            field=models.IntegerField(choices=[(0, 'N/a'), (1, 'Work f/home'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6'), (8, '7')], default=5, help_text='Number of office days per week'),
        ),
    ]
