# Generated by Django 4.2.11 on 2024-03-11 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0004_job_employer_alter_job_bring_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(help_text='pay for the job', validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
