# Generated by Django 4.2.11 on 2024-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0005_alter_job_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Employer',
            new_name='employer',
        ),
        migrations.AlterField(
            model_name='job',
            name='freelance_hire',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Freelance'), (2, 'Employed')], default=0, help_text='If you will be invoicing the company or hired as an employee'),
        ),
    ]
