# Generated by Django 4.2.11 on 2024-03-12 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0006_rename_employer_job_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bring_pet',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='- Whether pets are allowed in the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='child_care',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='available close to the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='commute_time',
            field=models.IntegerField(default=0, help_text='in minutes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='freelance_hire',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Freelance'), (2, 'Employed')], default=0, help_text='- Invoicing the company vs hired as an employee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='full_time_percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='holiday_days',
            field=models.IntegerField(default=20, help_text='per year', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='', help_text='Otional notes'),
        ),
        migrations.AlterField(
            model_name='job',
            name='office_days',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Work f/ home'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6'), (8, '7')], default=5, help_text='per week'),
        ),
        migrations.AlterField(
            model_name='job',
            name='office_type',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Open'), (2, 'Cubicle'), (3, 'Private')], default=0, help_text='layout'),
        ),
        migrations.AlterField(
            model_name='job',
            name='own_computer',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='- Whether you need to bring your own computer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='pet_sitter',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Yes'), (2, 'No')], default=1, help_text='available close to the office'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibility',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Manager'), (2, 'Supervisor'), (3, 'Team Leader'), (4, 'Employee')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_type',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Fixed'), (2, 'Flexible'), (3, 'Remote')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='starting_time',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, '6:00'), (2, '6:30'), (3, '7:00'), (4, '7:30'), (5, '8:00'), (6, '8:30'), (7, '9:00'), (8, '9:30'), (9, '10:00'), (10, '10:30'), (11, '11:00'), (12, '11:30'), (13, '12:00'), (14, '12:30'), (15, '1:00'), (16, '1:30'), (17, '2:00'), (18, '2:30'), (19, '3:00'), (20, '3:30'), (21, '4:00'), (22, '4:30'), (23, '5:00'), (24, '5:30'), (25, '6:00'), (26, '6:30'), (27, '7:00'), (28, '7:30'), (29, '8:00'), (30, '8:30'), (31, '9:00'), (32, '9:30'), (33, '10:00'), (34, '10:30'), (35, '11:00'), (36, '11:30'), (37, '12:00'), (38, '12:30'), (39, '1:00'), (40, '1:30'), (41, '2:00'), (42, '2:30'), (43, '3:00'), (44, '3:30'), (45, '4:00'), (46, '4:30'), (47, '5:00'), (48, '5:30')], default=0, help_text='of the work day'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'n/a'), (1, 'Considering'), (2, 'Applied'), (3, 'Interviewing'), (4, 'Rejected'), (5, 'Accepted')], default=0, help_text='of the job application'),
        ),
    ]
