# Generated by Django 4.2.22 on 2025-06-21 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0007_alter_job_bring_pet_alter_job_child_care_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='Optinal notes'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
